services:
    php:
        image: api/date
        ports:
            - 9000:9000
        volumes:
            - .:/app
    apache:
        image: bitnami/apache:latest
        ports:
            - 80:8080
        volumes:
            - ./apache-vhost/app.conf:/vhosts/app.conf:ro
            - .:/app
        depends_on:
            - php
